fix: missing space between author name and date
denoland/deno_blog pull request #40
Opened 2022-07-08 06:39 UTC by yidingww

This PR does 2 things:
 
1. fixed https://github.com/denoland/deno_blog/issues/39
2. add a shortcut to run testdata project locally by running `deno task demo`

2022-07-09 13:53 UTC, bartlomieju commented
Please rebase @yidingww

2022-07-09 16:44 UTC, yidingww commented
@bartlomieju did another commit https://github.com/denoland/deno_blog/pull/40/commits/0896166f6e3572085f6418eee1c524a47277cff0 to allow custom localised `dateFormat` (and removed `timezone`). IMO, setting a `dateFormat` is more **explicit** than setting a "timezone" and the users will have more controls. And it support localisation by default based on the `lang` setting :) 

also, I updated the test case a bit.

2022-07-09 18:12 UTC, ije commented on deps.ts
> +import dayjs from "https://esm.sh/dayjs@1.11.3";
please use `Intl.DateTimeFormat` instead of dayjs

2022-07-09 18:19 UTC, ije requested changes

2022-07-09 18:19 UTC, ije commented on blog.tsx
> -      colorScheme: blogState.theme ?? "auto",
please use the destructuring assignment `{ ...sharedHtmlOption, title: blogstate.title }`

2022-07-10 02:50 UTC, ije approved these changes
LGTM, thanks!

2022-07-10 02:51 UTC, merged

2022-07-10 02:53 UTC, yidingww commented
@ije Just an additional question: are we expecting a new release soon? Since there are quite a few new features merged recently 🤔